### ISSUE TITLE
Should migrate schema.json

### ISSUE THREAD

**Issue by kingthorin** [enthec/webappanalyzer#1]
It would probably be a good idea for this repo to include the latest schema.json from the original project.

**Comment by enthec-opensource** [comment]
You are right! nice catch, added on https://github.com/enthec/webappanalyzer/commit/76800f26863b8f663e211a676d8dda84629db524

we will start working on workflows and validators next week, as well as a good documentation and some contributing rules for the community
Thank you for your issue!
