### ISSUE TITLE
Wagtail regex error

### ISSUE THREAD

**Issue by AlexMili** [enthec/webappanalyzer#103]
**Platform**
MacOS 12.7 with python 3.10.

**Describe the bug**
The **Wagtail** DOM regexs `[style*='images/']`, `img[src*='images/']`, etc. Are not compiling in python 3.10.

**To Reproduce**
```python
import re
re.compile("(?:\\.[a-z]+|/media)(?:/[\\w-]+)?/(?:original_images/[\\w-]+|images/[\\w-.]+\\.(?:(?:fill|max|min)-\\d+x\\d+(?:-c\\d+)?|(?:width|height|scale)-\\d+|original))\\.")
```

**Expected behavior**
The regex should compile.

**Additional context**
The source of the bug is `[\\w-.]`. When modified to `[\\w-\\.]` everything works accordingly. Before doing a PR fixing this problem, I wanted to be sure I didn't miss something about how Javascript regexs work.

**Comment by kingthorin** [comment]
The DOM elements aren't regex, they're DOM selectors.

**Comment by AlexMili** [comment]
Arf, you're totally right. After taking that into account I don't have the error anymore. Thks !
