### ISSUE TITLE
Python regex compilation errors

### ISSUE THREAD

**Issue by AlexMili** [enthec/webappanalyzer#104]
**Platform**
macOS 12.7 with Python 3.10.

**Describe the bug**
After my [last Issue](#103), I tried to test ALL regex with python and found 3861 errors.

**To Reproduce**
See this [gist](https://gist.github.com/AlexMili/24b5c6a1b85fcc5e83d593c49e721bfe)

**Expected behavior**
All regex should compile in Python

**Additional context**
No

**Comment by MinhPham123456789** [comment]
Hi Alex, I am new to this Webappanalyzer, the README does not give much instruction on how to apply this database in coding and I saw this issue talking about how to use apply it in a Python program. Can you help me explain how one can use the json database to analyze a website technology?

**Comment by kingthorin** [comment]
The "DOM" elements aren't regex. They're DOM selectors.
