### ISSUE TITLE
ZAP use of webappanalyzer

### ISSUE THREAD

**Issue by psiinon** [enthec/webappanalyzer#7]
Hiya [ZAP](https://www.zaproxy.org/) team here (inc @thc202, @kingthorin, @ricekot),

As you may know we have a ZAP add-on which wraps the old Wappalyzer functionality: https://www.zaproxy.org/docs/desktop/addons/technology-detection/

Obviously this is not now being updated ☹️ 

Are you ok with us migrating to use webappanalyzer instead?
We will update that link to give you credit.

FYI we have a [github action](https://github.com/zaproxy/zap-extensions/blob/main/.github/workflows/create_wappalyzer_update.yml) which automatically pulls the source. This also has some unit tests - we've found bugs in Wappalyzer regexes quite a few times, and always report these back 😁

**Comment by enthec-opensource** [comment]
Hi!
We would love to see webappanalyzer as part of ZAP
We decided to maintain the technology list for the community and integration with other tools that we use
Zap has a big community and we would greatly appreciate your feedback to help improve this repo :)
