### ISSUE TITLE
`await wappalyzer.destroy();` hangs forever

### ISSUE THREAD

**Issue by sneko** [enthec/webappanalyzer#74]
**Platform**
MacOS

**Describe the bug**
After `await wappalyzer.init();` if I do a `await wappalyzer.destroy();` it hangs forever despite checking I'm calling it the right way.

When doing `console.log(wappalyzer.destroy)` I get `[AsyncFunction: destroy]`.

It was in their last public documentation https://www.npmjs.com/package/wappalyzer/v/6.10.66 so I don't understand what I'm doing wrong 😢 .

**Additional context**
Version `v6.10.66`

**Comment by enthec-opensource** [comment]
Hi @sneko !
This repo only supports the techs detectors, not the js implementation.
The lib you've just sent seems to be deprecated so i would suggest to use another js implementation of wappalyzer or pay for the official wappalyzer API.
