### ISSUE TITLE
IIS technology CPE typo/correction

### ISSUE THREAD

**Issue by Tazmaniac** [enthec/webappanalyzer#94]
The CPE for IIS is defined in actual signatures as
cpe:2.3:a:microsoft:internet_information_server:*:*:*:*:*:*:*:*

It should be 
cpe:2.3:a:microsoft:internet_information_services:*:*:*:*:*:*:*:*

**Comment by kingthorin** [comment]
https://github.com/nmap/nmap/issues/2401 seems to agree.

**Comment by kingthorin** [comment]
Seems to be a single line change: https://github.com/enthec/webappanalyzer/blob/239a27296d3f9e7c0b4e10dbf43e0d0fb76687e3/src/technologies/i.json#L58
